# Generated by Django 4.2.27 on 2026-07-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='daily_target_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
