# Generated by Django 4.2.27 on 2026-07-30 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_target_minutes',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='english_level',
            field=models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper-intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], default='A1', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(check=models.Q(('daily_target_minutes__gte', 5), ('daily_target_minutes__lte', 480)), name='profile_daily_target_between_5_and_480'),
        ),
    ]
