# Generated by Django 4.2.27 on 2026-08-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_daily_target_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Asia/Ho_Chi_Minh', max_length=64),
        ),
    ]
