# Generated by Django 4.2.27 on 2026-08-09 09:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('speaking', 'Speaking'), ('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar')], max_length=20)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)])),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('studied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-studied_at'],
                'indexes': [models.Index(fields=['user', 'studied_at'], name='study_user_date_idx'), models.Index(fields=['user', 'activity_type'], name='study_user_type_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(check=models.Q(('duration_minutes__gte', 1)), name='study_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(check=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 100)), _connector='OR'), name='study_score_between_0_and_100'),
        ),
    ]
