# Generated by Django 4.2.27 on 2026-08-16 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=150)),
                ('meaning', models.TextField()),
                ('translation', models.CharField(blank=True, max_length=255)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('phrase', 'Phrase'), ('phrasal_verb', 'Phrasal Verb'), ('other', 'Other')], default='other', max_length=20)),
                ('example_sentence', models.TextField(blank=True)),
                ('mastery_level', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('familiar', 'Familiar'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'mastery_level'], name='vocab_user_mastery_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vocabulary',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='unique_vocabulary_word_per_user'),
        ),
    ]
