# Generated by Django 4.2.27 on 2026-08-10 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_date', models.DateField()),
                ('target_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-target_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailygoal',
            constraint=models.UniqueConstraint(fields=('user', 'target_date'), name='unique_daily_goal_per_user_date'),
        ),
        migrations.AddConstraint(
            model_name='dailygoal',
            constraint=models.CheckConstraint(check=models.Q(('target_minutes__gte', 5), ('target_minutes__lte', 480)), name='daily_goal_target_between_5_and_480'),
        ),
    ]
